inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 2.6.2
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - bin/console
    - Rakefile
    - Gemfile
    - symbiont-ruby.gemspec

Metrics/LineLength:
  Max: 120

Style/RedundantBegin:
  Enabled: false
