inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 2.4.3
  Include:
    - lib/**/*
    - spec/**/*
    - bin/console
    - Rakefile
    - Gemfile
    - symbiont-ruby.gemspec

Metrics/LineLength:
  Max: 120
