inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 3.0.0
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - bin/console
    - Rakefile
    - Gemfile
    - symbiont-ruby.gemspec

Layout/LineLength:
  Max: 120

# NOTE: for code examples in tests
Lint/EmptyBlock:
  Exclude:
    - spec/**/*.rb

Style/RedundantBegin:
  Enabled: false

# NOTE: for code clarity in tests
RSpec/LeakyConstantDeclaration:
  Enabled: false
