---
os: linux
dist: xenial
language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
- 2.7
- ruby-head
before_install: gem install bundler
cache: bundler
script:
- bundle exec rake rubocop
- bundle exec rake yardoc
- bundle exec rake rspec
